// This file is generated by Astro DB
declare module 'astro:db' {
	export const WaitingList: import("@astrojs/db/runtime").Table<
		"WaitingList",
		{"id":{"type":"number","schema":{"unique":false,"deprecated":false,"name":"id","collection":"WaitingList","primaryKey":true}},"email":{"type":"text","schema":{"unique":true,"deprecated":false,"name":"email","collection":"WaitingList","primaryKey":false,"optional":false}}}
	>;
}
